version: '3'
services:
  postgres:
    container_name: movies
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
      - ./internal/repository/init.sql:/docker-entrypoint-initdb.d/init.sql